name: Ben Harkins
favicon: null
layout_spectrum: 0.37537567247636616
typography_spectrum: 0.11109442752785981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9423068929463625
  lightness: 0.797980688046664
  saturation: 0.6349248944316059
  rhythmicContrast: 0.08299714466556907
purpose: []
